apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5botScaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5bot.py
  minReplicas: 0
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60