apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5botscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5bot
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60