apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: saeed
spec:
  tls:
    - hosts:
      - saeed-bot.atech-bot.click
      secretName: saeed-tls-secret-f
  ingressClassName: saeed-nginx
  rules:
    - host: saeed-bot.atech-bot.click
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: polybot
              port:
                number: 8443