apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: server
          image: saeedwh/polybotk8s:28
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_APP_URL
              value: "https://saeed-bot.atech-bot.click:443"
      resources:
        limits:
          cpu: "100m"  # 100 milliCPU
          memory: "100Mi"  # 100 megabytes
        requests:
          cpu: "100m"  # 100 milliCPU
          memory: "100Mi"  # 100 megabytes
        readinessProbe:
          httpGet:
            path: /is_alive
            port: 8443
        livenessProbe:
          httpGet:
            path: /is_healthy
            port: 8443


---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
