apiVersion: v1
kind: Pod
metadata:
  name: polybot
  labels:
    app: polybot
spec:
  containers:
  - name: server
    image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
    ports:
      - containerPort: 8443
    env:
      - name: PORT
        value: "8443"
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
    livenessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: "/is_healthy"
        port: 8443
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
       path: "/is_alive"
       port: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: polybot
spec:
  selector:
    app: polybot
  ports:
  - name: http
    port: 60
    targetPort: 8443