apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: server
          image: saeedwh/polybotk8s:23
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_APP_URL
              value: "https://saeed-bot.atech-bot.click:443"
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi


---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 91
      targetPort: 8443
  type: ClusterIP
