apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5bot
spec:
  selector:
    matchLabels:
      app: yolo5bot
  template:
    metadata:
      labels:
        app: yolo5bot
    spec:
      containers:
        - name: server
          image: saeedwh/yolok8s:16
          ports:
            - containerPort: 8008
          env:
            - name: BUCKET_NAME
              value: "saeedphotobucket"
            - name: SQS_QUEUE_NAME
              value: "saeed_aws-project_SQS"

          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/is_alive"
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/is_ready"
              port: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: yolo5bot
spec:
  selector:
    app: yolo5bot
  ports:
  - name: http
    port: 8008
    targetPort: 8008